package br.edu.unisales.atendimento.config;
import br.edu.unisales.atendimento.security.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.*; import org.springframework.http.HttpMethod; import org.springframework.security.authentication.*; import org.springframework.security.authentication.dao.DaoAuthenticationProvider; import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.web.SecurityFilterChain; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter; import org.springframework.web.cors.*; import java.util.List;
@Configuration @EnableMethodSecurity
public class SecurityConfig{
 private final JwtAuthenticationFilter jwt; private final CustomUserDetailsService uds; private final RestAuthenticationEntryPoint entryPoint; private final RestAccessDeniedHandler deniedHandler; @Value("${app.cors.allowed-origin}") private String origin;
 public SecurityConfig(JwtAuthenticationFilter jwt,CustomUserDetailsService uds,RestAuthenticationEntryPoint entryPoint,RestAccessDeniedHandler deniedHandler){this.jwt=jwt;this.uds=uds;this.entryPoint=entryPoint;this.deniedHandler=deniedHandler;}
 @Bean SecurityFilterChain securityFilterChain(HttpSecurity h)throws Exception{return h.csrf(c->c.disable()).cors(c->c.configurationSource(corsConfigurationSource())).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/auth/**","/swagger-ui/**","/swagger-ui.html","/v3/api-docs/**").permitAll().requestMatchers(HttpMethod.POST,"/api/atendentes/**").hasRole("ADMIN").anyRequest().authenticated()).exceptionHandling(e->e.authenticationEntryPoint(entryPoint).accessDeniedHandler(deniedHandler)).authenticationProvider(authenticationProvider()).addFilterBefore(jwt,UsernamePasswordAuthenticationFilter.class).build();}
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean AuthenticationProvider authenticationProvider(){DaoAuthenticationProvider p=new DaoAuthenticationProvider();p.setUserDetailsService(uds);p.setPasswordEncoder(passwordEncoder());return p;}
 @Bean AuthenticationManager authenticationManager(AuthenticationConfiguration c)throws Exception{return c.getAuthenticationManager();}
 @Bean CorsConfigurationSource corsConfigurationSource(){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(List.of(origin));c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("*"));c.setAllowCredentials(true);UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
}
